### ISSUE TITLE
Multiple Hermes on a single Kafka cluster - management lacks namespaces support

### ISSUE THREAD

**Issue by mpac123** [allegro/hermes#1190]
Management module doesn't seem to support namespaces when running multiple Hermes on a single Kafka cluster (as described [here](https://hermes-pubsub.readthedocs.io/en/latest/configuration/kafka-and-zookeeper/#multiple-hermes-on-single-kafka-cluster)).

When running multiple instances of consumers + frontend + management, each triple in a distinct namespace, we observed that creating a group + topic from the console in a namespace results in creating a copy of this topic for every namespace. While frontend and consumers modules indeed send/consume messages only to/from their namespaces, the management doesn't seem to distinguish between namespaces and, as a result, the console is identical for every namespace and changes in one of them influence the others.

**Comment by druminski** [comment]
@mpac123 please take a look on #1191 which extends documentation about how this feature should be used. If you use shared Zookeeper cluster for all Hermes clusters then you also have to configure `zookeeper.rootPath` property in **Frontend**, **Consumers** module and `storage.pathPrefix` in *Management*. Otherwise your Hermes clusters will be sharing information about topics and subscriptions. Please also let us know if this was the problem, so we can close the issue :)

**Comment by mpac123** [comment]
@druminski yes, this was the exact problem, after following the configuration steps in the documentation extension you provided, everything works like a charm :) 
You can close the issue, thank you!
