### ISSUE TITLE
Schema registry subject names don't conform to the -value convention

### ISSUE THREAD

**Issue by mpac123** [allegro/hermes#1205]
Hi!
I have noticed that Hermes doesn't conform to the SR subject naming convention of using the topic name with -key or -value suffix, and it makes it a bit difficult to integrate Hermes with other tools that do. Do you think it would be possible to e.g. make it configurable?

**Comment by druminski** [comment]
Hey Marta,

Hermes doesn’t use a key in [`RecordProducer`](https://github.com/allegro/hermes/blob/d8dd808b48419acb2e141a40680210ca62ff7059/hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducer.java#L60) in kafka-producer, so it also doesn’t need `<topic>-key` schema. However I understand that `SchemaRegistry` has adopted this naming convention and other tools may require it. Therefore I think it’s a good idea to add support for suffix `-value` in schema names and make it enabled/disabled.

Would you like to add it or do you need help with it?

Btw. out of curiosity with which tools did you have problems due to lack of schema-registry naming convention?

**Comment by mpac123** [comment]
Hi Łukasz,

Thank you for a quick response! I'll be glad to contribute.

Regarding your question, in my team, we're developing a tool that relies on this naming strategy, as it allowed us to integrate easily with tools such as [landoop](https://hub.docker.com/r/landoop/kafka-lenses-dev/) or [akhq](https://akhq.io/). 
Now, we're considering Hermes as an alternative, and while we could obviously adapt our tool, we were thinking that adding this support to Hermes would be more straightforward and could prove to be useful in the future also for somebody else since it seems to have become a standard.

**Comment by lciolecki** [comment]
SchemaRegistry has naming convention like:
- schema value: {topic} -value
- schema key: {topic} -key

It will be nice if Hermes supports this convention :)
