### ISSUE TITLE
Topic removal should be forbidden if the topic contains any subscription

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1266]
Hermes-management should not allow to remove the topic and its schema when the topic contains any subscription. In that case Hermes-management should return a response with 403 status code and clear message.

**Comment by mohammedtabish** [comment]
Hey, wanted to take this up, in Kafka we cannot know directly how many consumers are attached to a topic but if we know the consumer groups then we can fetch the topic they are attached to so if there's any other good way please add on.
ps:- Sorry if I sounded stupid as I am at a beginner level but I would really like to work on it.

**Comment by druminski** [comment]
@mohammedtabish great choice :) In the first place take a look on [Hermes architecture](https://hermes-pubsub.readthedocs.io/en/latest/overview/architecture/). Hermes keeps information about its topics and subscriptions in a dedicated metadata store which is Zookeeper. It’s not the same Zookeeper used by Kafka (can be the same but we don’t recommend it). Therefore, before topic removal, we want to verify what is the number of subscriptions in Hermes Zookeeper. Take a look on [SubscriptionService](https://github.com/allegro/hermes/blob/ac3cb717b1dc67e226e794e920c0e1c3fe48dcc0/hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java#L96) class as Hermes already allows to list subscriptions for a topic.

**Comment by mohammedtabish** [comment]
During topic removal, we are first calling the schema removal from avro registry , and then checking the topicProperties if removal is allowed so in this case should we remove the schema before checking the active subscriptions?

**Comment by druminski** [comment]
Good question, I think at the beginning we should validate whether number of subscription is equal to zero. If this assertion is false then we should stop further execution and return 403 without schema remove.

**Comment by mohammedtabish** [comment]
Also should the state of the Subscription matters in this case i.e should we count only the number of ACTIVE and PENDING subscriptions?

**Comment by druminski** [comment]
Let’s count all subscriptions with any state.

**Comment by mohammedtabish** [comment]
When you are calling the remove topic API, it is internally calling the TopicRepository's implemented method in ZookeeperTopicRepository [removeTopic](https://github.com/allegro/hermes/blob/b33fe47ed073ed0958568e29eccc3b4fabae99ec/hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepository.java#L86) which is checking if the topicIsEmpty by calling [ensureTopicIsEmpty](https://github.com/allegro/hermes/blob/b33fe47ed073ed0958568e29eccc3b4fabae99ec/hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepository.java#L94) which is internally checking if it has any subscriptions and throwing the FORBIDDEN(403) exception if there is. So I think this issue is already implemented?

**Comment by druminski** [comment]
@mohammedtabish you are totally right. Thank you for the verification. In that case we could refactor this to make a validation of subscriptions number before topic schema remove. What do think about it, would you like to do it?

**Comment by mohammedtabish** [comment]
Okay I will create a pull request with my point of view, then you can check and tell me if you want it any other way.

**Comment by mohammedtabish** [comment]
My implementation would be, as we are already Autowiring the TopicRepository in the ZookeperTopicRepository we can call the ensureTopicIsEmpty method but this method is made private if we can change it to public then we can do that, as we can also do this your way by Autowiring the SubscriptionService and check the length of the list returned buy listSubscriptionNames but Autoriwiring the SubscriptionService just to call this method would be overkill because we can achieve the same by making the ZookeperTopicRepository's method public as it is already Autowired, let me know which way you wanna go I will implement it.

**Comment by druminski** [comment]
You convinced me to your proposition, let’s make `ensureTopicIsEmpty` public and call it in the TopicService.

**Comment by mohammedtabish** [comment]
Okay, my bad we are Autowiring the interface and there's no method named ensureTopicIsEmpty in that so making in public in ZookeeperTopicRepository won't work, making this method abstract by defining it in the interface and then overriding it in the ZookeeperTopicRepository and calling it in the TopicService , creating a PR. You can check if it is okay or not and then I will make changes your way.

**Comment by druminski** [comment]
No problem, I think we can expose this method in the interface as well.

**Comment by mohammedtabish** [comment]
Hey 1 test out of 390 is getting failed, please check my PR help we resolve this. Thanks
