### ISSUE TITLE
Hermes frontend sometimes returns incorrect status 200

### ISSUE THREAD

**Issue by faderskd** [allegro/hermes#1294]
Sometimes, under unknown conditions, Hermes Frontend returns a 200 response status code after publishing a message. It isn't returned normally. Allowed success status codes during publishing are 201, 202. When this situation happens Hermes Client does not treat this message as a successful one but does not make any retries too. When Hermes Frontend returns 200 status, the message body is empty. Maybe we should treat an empty body after publishing as a sign of error and despite proper status code, we should make a retry.

**Comment by druminski** [comment]
Thanks Daniel for the issue. Maybe we should investigate in what case Hermes-frontend returns 200 and instead of this status code we should return 500.

**Comment by faderskd** [comment]
Yes, I think so. If it would be too hard to reproduce this bug, we can directly change hermes client

**Comment by druminski** [comment]
I see that Hermes-frontend can return 200 due to default response in undertow. Hermes-frontend overwrite this default response for example in [MessageReadHandler class](https://github.com/allegro/hermes/blob/7907afb02503787760505cbfecca48369aa292f8/hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/MessageReadHandler.java#L199). But maybe there is a better way to disable this default response in the newest version of undertow.

**Comment by Diewa** [comment]
I have checked this problem and I haven’t able to reproduce this bug but as Łukasz said it is probably related with default response in Undertow. I’m not sure but I think that in some cases Hermes-frontend doesn’t override this default response for example in [MessageErrorProcessor class](https://github.com/allegro/hermes/blob/7907afb02503787760505cbfecca48369aa292f8/hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/end/MessageErrorProcessor.java#L63). 

This [PR](https://github.com/allegro/hermes/pull/1297) override an unexpected 200 status code and change it to 500.
