### ISSUE TITLE
Increase the width of the search bar

### ISSUE THREAD

**Issue by piotrrzysko** [allegro/hermes#1488]
Currently, the search bar is a bit small, we may consider making it wider:
![image](https://user-images.githubusercontent.com/6481553/162224323-86f833de-f4fb-42f3-a6ba-1102c9d00408.png)

**Comment by zzzzz1st** [comment]
I'll check that out.

**Comment by zzzzz1st** [comment]
Is this modification ok ?

**Comment by Rafal-Spryszynski-Allegro** [comment]
For me it is great. More than enough space to see those long topic names.
![image](https://user-images.githubusercontent.com/85548871/163536176-8d96c2a9-10a7-4443-8f67-e0349df67edc.png)

Although it is a bit inconsistent when seen on mobile:
![image](https://user-images.githubusercontent.com/85548871/163537941-38dd6ac6-082d-42f0-9d8a-b25c11218886.png)

versus previous:
![image](https://user-images.githubusercontent.com/85548871/163537957-6b9a211f-b99a-4f42-b313-4d30c9823778.png)

because all other screens use smaller margin.

**Comment by zzzzz1st** [comment]
Oh I see. That's because Search is not in a row. I'll modify and commit that again.

**Comment by zzzzz1st** [comment]
Modified. Please check it out now if it's good. Thanks.

**Comment by pitagoras3** [comment]
@zzzzz1st your new proposal looks great - I've approved your PR and merged it into `master` branch. Your change will be available in next Hermes release. Thank you for your cooperation!

**Comment by zzzzz1st** [comment]
Great. Thanks @pitagoras3
