### ISSUE TITLE
Migrate from apache oltu in hermes test helper

### ISSUE THREAD

**Issue by moscicky** [allegro/hermes#1679]
Apache oltu is no longer maintained since 2018. It uses javax namespace (cant use jakarta namespace with it). We should migrate to different ouath solution.

**Comment by a-wolk** [comment]
@szczygiel-m Hi, I've looked into this issue and found that Apache Oltu is used only in `package pl.allegro.tech.hermes.test.helper.oauth.server;` to create mock OAuth server. This server is used in `pl.allegro.tech.hermes.integration.OAuthIntegrationTest` to test retrieving tokens when sending messages to OAuth-secured subscribtions. Additionally, if I am not mistaken, tokens are just UUIDs randomly generated (`new OAuthIssuerImpl(new UUIDValueGenerator());`), so the issue is mostly about replacing data structures used by Apache Oltu with custom ones. I can try to do it.

**Comment by szczygiel-m** [comment]
Hi, thanks for the analysis, i will assign You 😄
