### ISSUE TITLE
Update endpoint resets fields to default values

### ISSUE THREAD

**Issue by dankraw** [allegro/hermes#199]
There's an issue with Topic update endpoint in management. When a field is updated, all other primitive type fields are being set to default values.
Example: I have a topic with `trackingEnabled=true`, `validation=false`. If I send PUT with  `{"validation":true}`, `trackingEnabled` will be reset to `false`.
This may refer to other "update" endpoints.

**Comment by alberskib** [comment]
The same problem could be observed during update of Subscription (and SubscriptionPolicy) via REST API. 
What is more there is no way to update any SubscriptionPolicy field alone without updating rate field. 
Requests like:
```
curl -X PUT -d '{"subscriptionPolicy": {"messageTtl":10}}' -H "Content-Type: application/json" http://10.10.10.10:8090/topics/com.example.events.clicks/subscriptions/clicks-receiver
```
result in Bad Request (400) with body 
```
{"message":"{javax.validation.constraints.Min.message} Subscription.subscriptionPolicy.rate must be greater than or equal to 1","code":"VALIDATION_ERROR"}
```. 
Root cause of the problem is the same.
