### ISSUE TITLE
Hermes for Point to Point communication

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#353]
Thanks for the wonderful framework that makes using Kafka simpler with a HTTP interface. 

However had a question, is it possible to use Hermes as a queue for Point to Point messaging. I have a use case where multiple consumers are processing from a message queue, and only one consumer has to pick the message for processing further.

Hopefully there is a way :)

**Comment by adamdubiel** [comment]
I don't have exact answer to your question, as i'm not sure if i understand the problem correctly, but you could take a closer look at [EndpointAddressResolver](https://github.com/allegro/hermes/blob/8ace9f3a8f2a680fbe91a7189f6b40f4cd43bd3e/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/EndpointAddressResolver.java) class which can be injected into `HermesConsumersBuilder`.

What it does, is associate given protocol (i.e. `p2p://`) to a address resolver. Having this kind of resolver, you can have all of your consumers hidden behind some logical name and resolved per message so that only one gets the message.

For example, you would create a subscription with `p2p://my-consumers` endpoint and your `EndpointAddressResolver` based on message and this name could change the logical name into some `http://my.consumer1.local:8080/`.

Let me know if this is even remotely close to what you had in mind :)

**Comment by gamefundas** [comment]
Your response made me think a little different with my approach. My "x" no. of consumer nodes are presently designed to work as listeners in the Active MQ world. However with Hermes or Kafka in general as a pub-sub replacing my MQ, I should expose them as a multi-node webservice (load balanced) and have these nodes process the messages.

Its a matter of how I see this. This should work. You can close this one out.

**Comment by adamdubiel** [comment]
That's exactly what i had in mind :) I proposed this `p2p://` protocol thing, as we use sth similar to load balance our traffic using [Consul](http://consul.io) as Service Discovery. Glad to help, let us know if you have any more questions :)
