### ISSUE TITLE
Integration of hermes frontend with Spring boot

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#426]
We are trying to integrate hermes frontend with spring boot application for service discovery/monitoring purpose. Please suggest me the best way to do it. 

Thanks.

**Comment by adamdubiel** [comment]
I think this would probably be quite easy, although maybe not too elegant. I would go with simple Spring Boot application, which in turn builds & starts `HermesFrontend` (built using `HermesFrontend.Builder`) in main. The configuration can be passed just as usual - Archaius shouldn't care if its Spring Boot. One thing to remember is either disable Spring Boot server or run it on different port than Frontend itself.

We do sth similar (adding service discovery), but we embed Hermes Frontend in simple application, not whole Spring Boot stack.

Do you want to expose Hermes metrics somehow via Spring Boot? Or what do you mean by monitor?

**Comment by gamefundas** [comment]
Adam, the idea is to manage and access these instances using Consul. Currently in our micro-service architecture all services are registered in Consul. Consumers simply use Service discovery to talk to other endpoints. Hermes is planned to be one such messaging endpoint.

Now Spring Cloud Consul has @EnableDiscoveryClient which simply registers a Boot application with Consul. Need to check if a simple boot app can be configured for Consul service discovery. Will give this a try and get back on this thread in case of any questions.

**Comment by adamdubiel** [comment]
Actually we use Consul internally as well. All we do is add startup and shutdown hooks and register instance using [Consul client](https://github.com/Ecwid/consul-api):

```
// registration object encapsulates Consul Client registration - nothing fancy
builder.withStartupHook((s) -> registration.register("hermes", port));
builder.withShutdownHook((s) -> registration.unregister());
```

I don't think you need Spring Boot magic here :)
It might be a good idea to add some `hermes-consul` module in the future, but it won't have high priority now, since we are moving towards [automatic registration  performed by Marathon](https://github.com/allegro/marathon-consul).

**Comment by gamefundas** [comment]
I realized after sending the message that we have got too lazy with Spring annotation based integration. :) This can be done with few lines of code as well.

Thanks to the startup hook it will allow us to initialize this easily. Also other things like stagemonitor which we use for non-prod to capture metrics on infra resources.

Now that you are already using Consul for Hermes it brings me an interesting question. Is there a way for the Consumer to use service discovery for the endpoint. This might be a useful thing when we use Kafka as an event bus within a micro-service kind of architecture. Perhaps you guys have already cracked this one. As I am trying to avoid the URL in the subscription. For external consumers the current mechanism works fine.

Look forward to your thoughts on this.

**Comment by adamdubiel** [comment]
This is exactly our usecase, i'm happy to share how we are doing this :)

There are actually 2 ways of achieving it using Consul. We are currently in migration phase from 1 to 2.

### 1. Pseudo protocol & using Consul API

Historically, we have `service://` pseudo protocol. It is used widely at our company to communicate using services logical names (as registered in Consul) instead of hosts & IPs. Our internal version of Hermes also supports it. Users register subscriptions with `service://my-service/some/endpoint` endpoints. When Consumers see the `service://` schema, they pass the address resolution to implementation of `EndpointAddressResolver`, which changes logical name into concrete host by asking Consul HTTP API (some caches are included of course) for list of hosts and selecting one (round robin).

You can register your own `EndpointAddressResolver` via:

```
// HermesConsumersBuilder
builder .withMessageSenderProvider("service", (s) -> // e.g. new ConsulAwareResolver() );
```

### 2. Using Consul DNS

You might be using Consul DNS already. We are planning to switch, thus replacing `service://` with `my-service.service.consul` calls. This means writing `EndpointAddressResolver` which would understand DNS SRV entries to extract host, port & priority. When we do it, we will probably share it in `hermes-consul` module, but i don't know any dates, so don't rely on us writing too much :)
