### ISSUE TITLE
inflight messages issue 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#460]
we are using elasticsearch for tracking and we are observing that few messages are marked inflight and few are success belong to same topic/ subscription. I believe this should not happen also does tracker updates the information in case the message is delivered from INFLIGHT to SUCCESS. 

 "hits": [
      {
        "_index": "sent_messages_2016_04_22",
        "_type": "sent_message",
        "_id": "AVQ-sINtFdi6dYiXi9Nd",
        "_score": 1,
        "_source": {
          "messageId": "923ba080-01d4-4615-9efa-ec24ae4b69c3",
          "batchId": "",
          "timestamp": 1461340631676,
          "publish_timestamp": 1461340631675,
          "topicName": "abc.topic",
          "subscription": "mySubscription_test_2",
          "status": "INFLIGHT",
          "offset": 803,
          "partition": 3,
          "cluster": "primary"
        }
      },
      {
        "_index": "sent_messages_2016_04_22",
        "_type": "sent_message",
        "_id": "AVQ-sINtFdi6dYiXi9Ni",
        "_score": 1,
        "_source": {
          "messageId": "36253f2f-189d-4ceb-9e33-79748dc56936",
          "batchId": "",
          "timestamp": 1461340631901,
          "publish_timestamp": 1461340631897,
          "topicName": "abc.topic",
          "subscription": "mySubscription_test_2",
          "status": "SUCCESS",
          "offset": 804,
          "partition": 0,
          "cluster": "primary"
        }
      },

**Comment by adamdubiel** [comment]
As per [documentation](http://hermes-pubsub.readthedocs.org/en/latest/user/subscribing/#message-tracking):  , `INFLIGHT` status on Consumers end means message was read from Kafka and is being sent to subscriber. Once it is sent, another entry (with `SUCCESS` status) is added in Elastic.
However if the message could not yet be delivered (i.e. because receiving service is unable to process the event) it will be retried and each retry should come with entry of `FAILED` status.

If you could filter Elastic entries by the message id of `923ba080-01d4-4615-9efa-ec24ae4b69c3` (the inflight one), what entries do you see?

**Comment by hikrrish** [comment]
Hi Adam,

I found the other entry with SUCCESS .. Thanks  we can close this one
