### ISSUE TITLE
Relax serial subscription max message TTL constraint

### ISSUE THREAD

**Issue by sslavic** [allegro/hermes#530]
It would be nice to have serial consumer subscription message max message TTL configurable, more relaxed, or even removed (as in batch subscriptions). What's the point of having retention policy in days and TTL up to two hours - I find it to be too limiting.

**Comment by adamdubiel** [comment]
You need to be aware why we have this limit. Once message is read from Kafka and it starts being retried, no message read afterwards (with higher offset) will be committed to Kafka. This is because offsets are linear in Kafka.

So, having 2 days of TTL, if there is just one message that is being retried, your last committed offset will be the one from 2 days ago. If you restart Consumers in the meantime, all messages from last committed offset will be sent once again.

All in all: having really high message ttl might not be so beneficial.

**Comment by sslavic** [comment]
Yes, I understand you may have different requirements, then at least please make it configurable, so we can adjust, because it's too low for us.

**Comment by adamdubiel** [comment]
Okay, we can do it if the risks are worth it :)

**Comment by druminski** [comment]
Closing it due to timeout, however we are open on contribution if this issue is still valid.
