### ISSUE TITLE
Consumer app crash frequently 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#586]
A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x00007ffa66d6a5a1, pid=2553, tid=140711929845504

 JRE version: Java(TM) SE Runtime Environment (8.0_77-b03) (build 1.8.0_77-b03)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 J 12488 C2 pl.allegro.tech.hermes.tracker.elasticsearch.consumers.ConsumersElasticsearchLogRepository.notEndedDocument(Lpl/allegro/tech/hermes/tracker/consumers/MessageMetadata;JLjava/lang/String;)Lorg/elasticsearch/common/xcontent/XContentBuilder; (102 bytes) @ 0x00007ffa66d6a5a1 [0x00007ffa66d69260+0x1341]

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /tmp/hs_err_pid2553.log
[thread 140711904581376 also had an error]
If you would like to submit a bug report, please visit:

0627807-5b60c9ef-leader-finder-thread" [_thread_blocked, id=22258, stack(0x00007ffa134f5000,0x00007ffa135f6000)]

did anyone experience  this issue ?

**Comment by adamdubiel** [comment]
Which version of Hermes are you running? I don't remember seeing anything like this. For the record, be we run on Java 1.8_41 on prod.

**Comment by hikrrish** [comment]
Hi Adam, 
we are using 0.8.6-HOTFIX version and I forget to post this issue in past, however we have seen this 5-6 times in different environments. we are running our servers in AWS. let me know if you need the fatal error log file /tmp/hs_err_pid2553.log

**Comment by hikrrish** [comment]
I suspect if elastic search logging is causing any issue, just to drill down, we have used custom loggers and removed elastic search log repository

**Comment by hikrrish** [comment]
@adamdubiel 
I know we can run multiple frontend and manager for failover, however can you tell me what will happen if we have multiple consumer nodes connected to same topics and subscriptions. Can it cause a duplicate message delivered for a subscription ?  though I have tried it and not received duplicate messages however wanted to confirm it with you

**Comment by adamdubiel** [comment]
We run a total of 4 consumers on one of our production clusters per datacenter :)

If you run 0.8.6 version, you probably use the "old" consumers algorithm, in which every Consumer tries to consume messages from every subscription. This is fine and no duplicates will be sent, because each instance connects to different partitions (Kafka way of doing things). So, if you have Consumer instances C1, C2 and C3 with some subscription X and topics with 8 partitions:

* C1 reads messages from partitions  1, 2, 3
* C2 reads messages from partitions 4, 5, 6
* C3 reads messages from partitions 7, 8

Of course this is just an example, but all in all you can spawn multiple instances of Consumers.

There is also a new workload algorithm: selective, which we introduced in 0.8.7 or 0.8.8, which is better for horizontal scalability. If you have a lot of subscriptions, in selective you can specify:

* how many subscriptions can one instance of Consumers handle
* how many instances of Consumers should read from single subscription

Then the available subscriptions are scattered throughout available Consumer instances. This is important if i.e. you have 4 consumer instances, but would like to have no more than two instances handling single subscription at a time. Taking example with C1, C2, C3 from previous paragraph and consumers-per-subsription parameter set to 2:

* C1 and C2 will handle subscription X (2 consumers)
* C3 and C1 might handle subscription Y (2 consumers)
* ... and so on, never more than 2 consumers per subsription

**Comment by hikrrish** [comment]
thanks, very well explained :)

**Comment by adamdubiel** [comment]
Closing this issue, hope you managed to resolve it :)
