### ISSUE TITLE
Consumers max-rate negotiation

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#588]
Currently the maximum rate at which each Consumers instance can send events is calculated:

```
consumer_max_rate = global_max_rate / consumers_count
```

This fails when:
- we have multiple DCs and traffic is not uniform (DC1 receives more events than DC2)
- lag is not uniformly distributed among partitions (i.e. one consumer blocked the partition and it now has much higher lag that others)

We need an algorithm that could dynamically adjust `consumer_max_rate` depending on the actual need. Things to watch out for:
- algorithm should be stable, i.e. it should try to preserve current state if possible

**Comment by chemicL** [comment]
The initial idea I have is be based on these assumptions:

- consumer tracks the actual rate.
- the rate is tracked in a zookeeper node (last `rate_history_size` observations are kept for smoothing).
- a coordinator role is needed for assigning `consumer_max_rate` to each consumer.

The algorithm is based on iterations at a constant `iteration_interval`.

Consumer's role:
- each consumer updates the rate in zookeeper at the given `iteration_interval`.
- every time a consumer updates it's rate in zookeeper, it also adjusts it's `consumer_max_rate` based on what the coordinator exposes for that instance.

Coordinator's role:
- every `iteration_interval` the coordinator sums up the `consumer_rate` values with regard to the history and by averaging the rates (moving average) calculates a `consumer_used_rate` factor.
- knowing all the details we can calculate new `consumer_max_rate` for each consumer by either taking away a bit of unused rate or by adding from the shared unused rate pool. In case there is nothing left, the values should be granted equal with this approach (so `consumer_max_rate = global_max_rate / consumers_count` as it is now)

More details follow.

Either of the two can happen:
1. `consumer_used_rate >= 1.0 - tolerance` - busy consumers
2. `consumer_used_rate < 1.0 - tolerance` - relaxed consumers

Let's consider each case separately:
1. take away from `consumer_max_rate`
- `consumer_used_rate` is levelled by a scale function for more smooth adjustments; e.g. `1 / (2 * consumer_used_rate) - 0.5` and strict stability limits are imposed when not to change one's `consumer_max_rate`. Let's call the result of scaling `consumer_scaling_factor`.
- `consumer_max_rate -= consumer_scaling_factor * (consumer_max_rate - consumer_used_rate)`.

Now, we sum up what we have left from all this subtracting and distribute it among the busy consumers.

2. add to `consumer_max_rate`
- based on the sum of all current `consumer_used_rate` we can calculate the `consumer_share` in the global rate for each consumer.
- new `consumer_max_rate` is calculated by subtracting the available rate multiplied by the `consumer_share` also penalized as described before and normalized

This is an initial outline and some details are missing. I just wanted to start a discussion.

**Comment by chemicL** [comment]
Note also, we can completely abandon the recalculation if there is no busy consumer.

Instead of using `consumer_scaling_factor` to select the amount of rate to take away from relaxed consumer and `consumer_share` for distributing rate among busy consumers, we can simply select a nominal unit of available rate.  A nominal unit can be added/subtracted per consumer in each iteration and the system should still balance itself out. Just using more iterations.

**Comment by adamdubiel** [comment]
I think we can continue with this implementation, we just have to look out for the situation when once consumer drops from zookeeper, like it happens (sometimes) with selective algorithm.

**Comment by Kornel** [comment]
Did you prepare maybe some simulation how the consumer rates would be affected? 

What I'm thinking of is a simple script which simulates e.g. 4-6 consumer instances, each of them with a slightly different characteristic and then on top of that I'd run your proposed algorithm to see how it affect's the consumer rates. I'd code the simulated consumers in such a way that they would respond to lower/higher rates without or with trouble. 

This would help to see a) how the proposed algorithm behaves b) is the moving average a good choice, maybe you should take some percentile of the last n measured rates? c) and I think it'd really fun to do :)

On the other hand we can run this simulation on the test env, but I think playing around with such a simulation might reveal some interesting observations.

**Comment by chemicL** [comment]
So far I have prepared the plumbing code for distributing the max-rate using zookeeper across the nodes by using a 1/N approach. You can check it out on the branch `consumers-rate-negotiation`.

I was also thinking about tuning the algorithm via some simulations, but I decided not to for now and to base possible tunings on actual traffic by recording the behaviour via metrics.

Having some metrics on how our subscriptions behave over time we can extract the parameters and run these simulations to do the fine tuning.

Regarding moving average - actually for now I'm assuming an average of last 3 observations (tuneable) and will definitely investigate more whether weighing them makes sense, or perhaps just the last observation is significant?

During the plumbing phase I discovered some edge scenarios which would not have been taken into account in the ideal algorithm setting, which assumes all consumers are present at time of calculation and behave well. Now having learned that there are some things to consider - e.g. what happens if a consumer can't (at this moment in time) fetch it's current max rate? I think the simulations we create will be much more reflective of reality.

I'll keep you posted :-)

**Comment by Kornel** [comment]
Thanks for the thorough explantation, I'm sure there are lots of
intricacies:)
On Fri, 14 Oct 2016 at 10:17, Dariusz Jedrzejczyk <notifications@github.com>
wrote:

So far I have prepared the plumbing code for distributing the max-rate
using zookeeper across the nodes by using a 1/N approach. You can check it
out on the branch consumers-rate-negotiation.

I was also thinking about tuning the algorithm via some simulations, but I
decided not to for now and to base possible tunings on actual traffic by
recording the behaviour via metrics.

Having some metrics on how our subscriptions behave over time we can
extract the parameters and run these simulations to do the fine tuning.

Regarding moving average - actually for now I'm assuming an average of last
3 observations (tuneable) and will definitely investigate more whether
weighing them makes sense, or perhaps just the last observation is
significant?

During the plumbing phase I discovered some edge scenarios which would not
have been taken into account in the ideal algorithm setting, which assumes
all consumers are present at time of calculation and behave well. Now
having learned that there are some things to consider - e.g. what happens
if a consumer can't (at this moment in time) fetch it's current max rate? I
think the simulations we create will be much more reflective of reality.

I'll keep you posted :-)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/allegro/hermes/issues/588#issuecomment-253737691>, or mute
the thread
