### ISSUE TITLE
Avro messages does not contain header (confluent schema registry)

### ISSUE THREAD

**Issue by peick** [allegro/hermes#682]
When using confluent schema registry, serialized avro messages must contain a header to make sure messages can be processed with default confluent's tools.

This avro header is missing in hermes messages:
- posting messages to a topic with such a header results in a validation error.
- json2avro does not contain them
- the validation tool also revokes such messages

In the confluent schema registry the related code is this: https://github.com/confluentinc/schema-registry/tree/master/avro-serializer/src/main/java/io/confluent/kafka/serializers

Affected hermes version: 0.10.2

**Comment by adamdubiel** [comment]
You mean the "magic bytes" with schema version? We don't use it much, services send this information in form of `Schema-Version` header. If you would like to add support to this magic bytes a PR would be very welcome so you could test it as well, otherwise it will probably wait some time. If you need help in figuring out what needs to be changed we will be happy to help.

**Comment by peick** [comment]
Thanks for your quick response.

Yes, I meant exactly that: magic byte + schema id. I/We will work out a solution and create a PR.

**Comment by adamdubiel** [comment]
Based on current development in [Avro single-message encoding](https://issues.apache.org/jira/browse/AVRO-1704) i think we might consider implementing support for this encoding. Don't know if we will extend this support to Confluent encoding. Stay tuned!
