### ISSUE TITLE
Configure max.message.size on Kafka with data from Topic

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#744]
Hermes has own max message size constraints, but we do not send this data to Kafka. We should set max.message.size property on Kafka topics using data from Topic.

**Comment by mictyd** [comment]
I tried to do this, but it turns out I don't really understand the issue ;)
You can set maximum message size on Kafka broker, but it's global setting on Kafka cluster, not per topic. 
On the other hand, we could set  maximum size of message on `Producer`object. This setting is passed during constructing object though, so we would need one Producer per Topic - what would need much more resources. Additionally, we would have to re-create Producer every time max.message.size changes on Topic.
Can you clarify a little bit what you meant creating this issue?

**Comment by adamdubiel** [comment]
What we wanted was to set this property on topic creation/update: https://kafka.apache.org/documentation/#topicconfigs (it can be done).

**Comment by mictyd** [comment]
Oh, now I understand :) I'll take it then :)
