### ISSUE TITLE
Question | EndPoint resolver on consumer

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#843]
version 0.10.1
We have created a ConsulAwareEndpointResolver to resolve the consul based (custom protocol ) addresses. Could you please provide answers to following :
do we need to include additional protocols in management configuration along with service protocol 
e.g.  service, http, https or I can assume it would by default support http/https ?

we have provided consulAware listener as part of consumer startup, do we need to provide http/https endpoint resolver or they are by default added in the list of resolvers ?

The issue we are facing is address resolution for a CNAME address, where consumer is not able to resolve to a correct address and throwing unknown host exception, this is a https URL, when I tried to use a custom resolver it was giving me cert exception, I disabled cert validation and peer cert validation still seeing same exception, I think I need to use SSL context without hostname verifier I am not sure if thats configurable, I am curious to understand why is not able to resolve to a correct address will provide you logs and other details in case you need it.

**Comment by gamefundas** [comment]
@adamdubiel it appears Jetty HttpClient is trying to resolve the hostname/cname to an IP address of the subscriber URL. The problem with this is that the certificates are validated against the fully qualified URL containing the domain name. 

So far all our pubsub messaging was internal and they were working fine. This is the first time we are publishing something to an external application URL. 

Your inputs on this could prove to be very helpful. 

Thanks
Andy

**Comment by adamdubiel** [comment]
I don't know how your implementation of custom resolver look like, but what we do is (i think i described it in some other issues):

* for hosts which need Consul resolution URL is: `service://<service-name>`
* for "normal" hosts: `http://myhost.net` (or `https`)

We use second case to communicate with some https hosts with valid certs and seen no problem with this. However i know we added some additional https cert settings in [0.10.2](https://github.com/allegro/hermes/blob/master/CHANGELOG.md#666-options-to-configure-consumer-http-client-ssl-context) - maybe it would fix the problem?

**Comment by gamefundas** [comment]
The consul resolver works fine in case of service:// but for http/https the default r solver strangely resolves “host.net” to its own (consumer) IP address.

**Comment by gamefundas** [comment]
This happened to be a freaky DNS configuration issue on our side. The jetty client for some reason in its debug log printed the consumer IP address adding to the confusion. Once we reconfigure the DNS and firewall rules today, we will test and confirm. For the most part this should be non-issue.

**Comment by gamefundas** [comment]
Partly a DNS issue but the real problem was with our Okhttp client, which introduced a lot of default HTTP headers like "Host", "Content-Length", "gzip encoding" etc. which freaks out our secured subscriber and an internal redirect fails to happen. This apparently terminates the connection at some point and we kept seeing HTTP response code "0" and response as null.

This one was hard to crack especially due to limited logging on the consumer side, but then adding some extra logging and enabling debug logging for Jetty httpclient revealed the problem. For now the fix is to limit the Metadata headers to only the ones defined in subscription. Metadata headers override extra headers giving us control to manage this externally on the subscription level.

**Comment by adamdubiel** [comment]
I will close this, as it was only a question.
